### ISSUE TITLE
Do i have to install babel-plugin-dotenv-import?

### ISSUE THREAD

**Issue by makearts** [goatandsheep/react-native-dotenv#16]
After i update to 2.2.0 i follow all ReadMe but it says cannot find module 'babel-plugin-dotenv-import'... so after i install that package it works fine is it normal?? 

And i have another question. when i read 'babel-plugin-dotenv-import' projects readme it is really same with this project. is there some relationship between both project??

**Comment by makearts** [comment]
> Looks like the documentation is copied from [babel-plugin-dotenv-import](https://github.com/tusbar/babel-plugin-dotenv-import) without updating. The correct babel plugin name would be `module:react-native-dotenv` and not `dotenv-import`.

oh thanks now i understand!! so is this same with "babel-plugin-dotenv-import" ? or have other performance?
