### PR TITLE
Update README to reference the correct plugin/module name

### LINKED ISSUE #16: Do i have to install babel-plugin-dotenv-import?
After i update to 2.2.0 i follow all ReadMe but it says cannot find module 'babel-plugin-dotenv-import'... so after i install that package it works fine is it normal?? 

And i have another question. when i read 'babel-plugin-dotenv-import' projects readme it is really same with this project. is there some relationship between both project??

### PR DESCRIPTION
**Pull request by ryanhefner**
I was running into the same issue as @makearts–and with @snmishra suggestion–this change fixed the issue I was running into.

Fixes #16 

It might also address, #15, but not sure if people are running into other issues in that one.

### CODE REVIEW

**Comment by teamzz111** [comment]
@wardoost  please merge
