### ISSUE TITLE
Does this library work with Expo SDK 49?

### ISSUE THREAD

**Issue by benazir46** [goatandsheep/react-native-dotenv#467]
### Discussed in https://github.com/goatandsheep/react-native-dotenv/discussions/465

<div type='discussions-op-text'>

<sup>Originally posted by **benazir46** October 14, 2023</sup>
### Discussed in https://github.com/goatandsheep/react-native-dotenv/discussions/465

<div type='discussions-op-text'>

<sup>Originally posted by **benazir46** October 14, 2023</sup>
I use a private package that uses environment variables. After upgrading to Expo SDK 49 from 48, they are not working properly in standalone builds. I'm accessing env variables like process.env.MY_VARIABLE. It works inside the src folder, but it's not working inside the node_modules folder where my private package lies. Expo SDK 49 supports environment variables starting with the prefix EXPO_PUBLIC_. Expo mentioned it does not change anything inside the node_modules folder for [security reasons](https://docs.expo.dev/guides/environment-variables/#how-variables-are-loaded), so I was hoping this library could help. I have been using this library for the last five years without any trouble till now. 

I'm also using Sentry. It needs environment variables too. In Expo SDK 48 I had issues with it: Sentry package wasn't able to access the env vars. The way I got around with was by updating the babel configuration like this:
<br/>

`    plugins: [
      [
        'module:react-native-dotenv',
        {
          moduleName: 'react-native-dotenv',
          path: '.env.custom',
          allowUndefined: false,
        },
      ],
    ]`

<br/>
Now it's not working. Could this be due to the eas-cli? My current version is `eas-cli/5.4.0 darwin-x64 node-v16.19.1`

To reproduce this you need to use Sentry and install a private package that uses env variables. Then check the env variable values inside the node_modules folder on the standalone build. Here is my expo environment info:
<br/>
  expo-env-info 1.0.5 environment info:

>     System:
>       OS: macOS 14.0
>       Shell: 5.9 - /bin/zsh
>     Binaries:
>       Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
>       Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
>       npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
>       Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
>     Managers:
>       CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
>     SDKs:
>       iOS SDK:
>         Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
>     IDEs:
>       Android Studio: 2022.3 AI-223.8836.35.2231.10811636
>       Xcode: 15.0/15A240d - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^49.0.13 => 49.0.13 
>       react: 18.2.0 => 18.2.0 
>       react-dom: 18.2.0 => 18.2.0 
>       react-native: 0.72.5 => 0.72.5 
>       react-native-web: ~0.19.6 => 0.19.9 
>     npmGlobalPackages:
>       eas-cli: 5.4.0
>     Expo Workflow: bare

</div>

</div>
